# This file runs the command for the analyses in Sarikaya et al (2016).
# The file was generated by SHC, May 4 2016
#
# The data was collected by Didem Sarikaya and is stored in the tab 
# delimited text file "data.txt", along with an ecology data file "eco.txt"
#
# Distributions of trees for these anlayses are stored in the files
# all_all_POSTERIOR.trees and new_mito_POSTERIOR.trees.
# 
# The output is written to files with the following IDs:
# all_all refers to analyses over 100 trees using all available sequence data
# mito referes to analyses over 100 trees using only mitochondrial data
# mouth, scapto, amc, and pna are group specific analyses
# Sari is only data collected by Sarikaya
# sp2 is using alternative proxy IDs
# t1 are PGLS adult data results, t2 are OUwie results, and t3 are PGLS larval results
#
# The analyses can be reproduced in R with the following packages installed:
library(corHMM)
library(OUwie)
library(surface)
library(nlme)
library(dplyr)
library(phytools)
set.seed(1234)

#module load gmp/6.1.0-fasrc01
#module load mpfr/3.1.3-fasrc01

### Transform the datasets ###

# Read in the dataset
### dat <- read.table("data.txt",header=T)

# Take average by species of each measurement
dat <- read.table("data.txt",header=T) 
groups <- dat %>% distinct(species,group)
dat <- dat %>% 	group_by(species) %>% 
	summarize_if(is.numeric,funs(mean),na.rm=T)

dat <- left_join(dat,groups,by="species")

# Load ecological data, sort into categories of oviposition substrate
eco <- read.table("ecological_classifications.txt",header=T)
# eco$reg = 8 regime model
# eco$reg2 = 3 regime model
# eco$reg3 = 2 regime model
eco$reg2 <- plyr::mapvalues(eco$reg,c("Fungus","Fruit","Generalist","Leaf","Flower","Sap","Spider"),c("gen","gen","gen","gen","Flower_Spider","gen","Flower_Spider"))
eco$reg3 <- plyr::mapvalues(eco$reg,c("Fungus","Fruit","Generalist","Leaf","Flower","Sap","Spider"),c("gen","gen","gen","gen","gen","gen","gen"))

# Merge these two data tables by species ID
mg <- merge(dat,eco,by="species")

# Write average tables, and log transform the data and write a table
write.table(mg,file="avgs.txt",row.names=FALSE,sep="\t")
avgs <- read.delim("avgs.txt")
# Take the natural log of each numerical column
logs <- avgs %>% mutate(
	thor = log(thorax),
	thor_vol = log(thor_vol),
	onum = log(onum),
	dors = log(dors),
	egg_vol = log(egg_vol),
	major = log(major),
	minor = log(minor),
	prop = log(prop),
	tf_num = log(tf_num),
	tfc_tf = log(tfc_tf),
	total_tfc = log(total_tfc))

write.table(logs,file="logs.txt",row.names=FALSE,sep="\t")

onum_logs <- logs %>% mutate(trait = onum)
prop_logs <- logs %>% mutate(trait = prop) %>% filter(!(is.infinite(trait)))
thvl_logs <- logs %>% mutate(trait = thor_vol)
eggs_logs <- logs %>% mutate(trait = egg_vol)



### This reads in the posterior distributions of phylogenetic trees, and then samples n number of trees for uncertainty estimates
sample_size <- 1000

# all genetic data trees
raw_all_trees <- read.nexus("nuc_mt_beast_posterior.trees")
all_trees <- sample(raw_all_trees,sample_size)

# mitocondrial only trees
raw_mito_trees <- read.nexus("mt_beast_posterior.trees")
mito_trees <- sample(raw_mito_trees,sample_size)




### This code calculates the phylogenetic residuals of log egg size and log ovariole number to log thorax volume, using one of the all_trees as a representative phylogeny 

# Reduce the dataset to only those species with data
reduced_logs <- logs %>% 
			filter(species %in% all_trees[[1]]$tip.label) %>%
			mutate(trait1 = egg_vol, trait2 = onum, indep = thor_vol) %>% 
			select(species,trait1,trait2,indep) %>% 
			na.omit()

# Build the dataframes to calculate phylogenetic residuals
Y <- data.frame(trait1 = reduced_logs$trait1, trait2 = reduced_logs$trait2 ,row.names=reduced_logs$species)
X <- reduced_logs$indep
names(X) <- reduced_logs$species

# The tree is pruned to include tips in the dataset
  pruned <- drop.tip(all_trees[[1]],tip=setdiff(all_trees[[1]]$tip.label,reduced_logs$species))

# The residuals are calculated
resid <- data.frame((phyl.resid(pruned,X,Y,method="BM")$resid))

# Update the main dataframe
logs <- left_join(logs,tibble::rownames_to_column(resid,var = "species"),by = "species") %>% rename(eggs_resid = trait1, onum_resid = trait2)

eggs_resid_logs <- logs %>% mutate(trait = eggs_resid)


### Functions for calling each program ###

# This reconstructs the ancestral ecological state with corHMM
# and fits evoutionary models using OUwie over many trees
OUwie.trees <- function(phy,eco_reg,model,dat){
	# The full tree is pruned to taxa with ecological data
	pp_pruned <- drop.tip(phy,setdiff(phy$tip.label,eco_reg$species))
	# corHMM, using hte rayDISC function, reconstructs ancestral states
	pp <- rayDISC(pp_pruned,eco_reg[,c(1,2)],model="ER",node.states="marginal")
	# this tree is pruned to those with reproductive data
	pruned <- drop.tip(pp$phy,setdiff(pp$phy$tip.label,dat$species))
	# OUwie calculates the best fit of the model
	results <- OUwie(pruned,dat,model,simmap.tree=FALSE,diagn=FALSE)
	return(results)
}

# This computes PGLS for two measurements over many trees
pgls.trees <- function(phy,dat,form){
	# The full tree is pruned to those with both reproductive traits
	pruned <- drop.tip(phy,setdiff(phy$tip.label,rownames(dat)))
	# The dataset is trimmed to only include those with data, just in case
	red_dat <- dat[!rownames(dat) %in% setdiff(rownames(dat),pruned$tip.label),]
	# PGLS is performed using an OU model and with a starting alpha very smal
	lm_str <- corMartins(0.000000001,phy=pruned)
	# the results are summarized
	outskis <- gls(as.formula(form),correlation = lm_str,data = red_dat,method="ML")
	return(outskis)
}

### Analyses ###

# This function runs the reproduced analyses in the study 
run_ouwie_analyses <- function(trees,logs,name){
	# These commands generate data tables formatted for each specific program
	# These commands subset to include the maximum data for each analysis
	# "NA" and "Inf" data points are omitted, and ecological states are set to numerical

	# In all of the following, onum = ovariole number, thvl = thorax volume
	# prop = proportional egg volume, eggs = egg volume, tf = terminal filament
	# tfc = terminal filament cell, tot = total

	### 8 state model

	ouwie_8state <- logs %>% select(species,reg,trait) %>% na.omit() %>% mutate(num_reg = as.numeric(reg))
	reg_8state_table <- ouwie_8state %>% distinct(reg,num_reg)
	eco_reg <- ouwie_8state %>% select(species,num_reg) %>% rename(reg = num_reg)

	# These commands call OUwie for 100 trees, using 3 models of evolution (BM1, OU1, OUM),
	#    and using 3 different systems of categorizing substrates (reg, reg2, reg3)

	BM1_ouwie_8state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="BM1",dat=ouwie_8state %>% select(species,num_reg,trait))
	OU1_ouwie_8state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="OU1",dat=ouwie_8state %>% select(species,num_reg,trait))
	OUM_ouwie_8state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="OUM",dat=ouwie_8state %>% select(species,num_reg,trait))

	### 3 state model

	ouwie_3state <- logs %>% select(species,reg2,trait) %>% na.omit() %>% mutate(num_reg = as.numeric(reg2))
	reg_3state_table <- ouwie_3state %>% distinct(reg2,num_reg)
	eco_reg <- ouwie_3state %>% select(species,num_reg) %>% rename(reg = num_reg)

	BM1_ouwie_3state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="BM1",dat=ouwie_3state %>% select(species,num_reg,trait))
	OU1_ouwie_3state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="OU1",dat=ouwie_3state %>% select(species,num_reg,trait))
	OUM_ouwie_3state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="OUM",dat=ouwie_3state %>% select(species,num_reg,trait))

	### 2 state model

	ouwie_2state <- logs %>% select(species,reg3,trait) %>% na.omit() %>% mutate(num_reg = as.numeric(reg3))
	reg_2state_table <- ouwie_2state %>% distinct(reg3,num_reg)
	eco_reg <- ouwie_2state %>% select(species,num_reg) %>% rename(reg = num_reg)

	BM1_ouwie_2state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="BM1",dat=ouwie_2state %>% select(species,num_reg,trait))
	OU1_ouwie_2state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="OU1",dat=ouwie_2state %>% select(species,num_reg,trait))
	OUM_ouwie_2state_out <- lapply(trees,OUwie.trees,eco_reg=eco_reg,model="OUM",dat=ouwie_2state %>% select(species,num_reg,trait))
	
	# These commands build dataframes from the results of the OUwie analysis
	t2_ouwie <- matrix(ncol=9,nrow=length(trees))
	colnames(t2_ouwie) <- c("BM1_8","BM1_3","BM1_2","OU1_8","OU1_3","OU1_2","OUM_8","OUM_3","OUM_2")

	for (i in 1:length(trees)){
		t2_ouwie[i,1] <- BM1_ouwie_8state_out[[i]]$AICc
		t2_ouwie[i,2] <- BM1_ouwie_3state_out[[i]]$AICc
		t2_ouwie[i,3] <- BM1_ouwie_2state_out[[i]]$AICc
		t2_ouwie[i,4] <- OU1_ouwie_8state_out[[i]]$AICc
		t2_ouwie[i,5] <- OU1_ouwie_3state_out[[i]]$AICc
		t2_ouwie[i,6] <- OU1_ouwie_2state_out[[i]]$AICc
		t2_ouwie[i,7] <- OUM_ouwie_8state_out[[i]]$AICc
		t2_ouwie[i,8] <- OUM_ouwie_3state_out[[i]]$AICc
		t2_ouwie[i,9] <- OUM_ouwie_2state_out[[i]]$AICc
	}

	OUM_ouwie_8state_theta <- matrix(nrow = length(trees), ncol = length(OUM_ouwie_8state_out[[1]]$theta))
	OUM_ouwie_3state_theta <- matrix(nrow = length(trees), ncol = length(OUM_ouwie_3state_out[[1]]$theta))
	OUM_ouwie_2state_theta <- matrix(nrow = length(trees), ncol = length(OUM_ouwie_2state_out[[1]]$theta))

	states <- reg_8state_table %>% arrange(num_reg) %>% pull(reg) %>% as.character()
	nam <- c(states,paste(states,"_se",sep=""))

	states <- reg_3state_table %>% arrange(num_reg) %>% pull(reg2) %>% as.character()
	nam2 <- c(states,paste(states,"_se",sep=""))

	states <- reg_2state_table %>% arrange(num_reg) %>% pull(reg3) %>% as.character()
	nam3 <- c(states,paste(states,"_se",sep=""))


	for (i in 1:length(trees)){
		OUM_ouwie_8state_theta[i,1:length(OUM_ouwie_8state_out[[i]]$theta)] <- (OUM_ouwie_8state_out[[i]]$theta)
		OUM_ouwie_3state_theta[i,1:length(OUM_ouwie_3state_out[[i]]$theta)] <- (OUM_ouwie_3state_out[[i]]$theta)
		OUM_ouwie_2state_theta[i,1:length(OUM_ouwie_2state_out[[i]]$theta)] <- (OUM_ouwie_2state_out[[i]]$theta)
	}

	colnames(OUM_ouwie_8state_theta) <- nam
	colnames(OUM_ouwie_3state_theta) <- nam2
	colnames(OUM_ouwie_2state_theta) <- nam3

	# This command writes the results to files
	write.table(file=paste(name,"t2.txt",sep="_"),t2_ouwie,row.names=F,sep="\t")
	write.table(file=paste(name,"t4_OUM_ouwie_8state_theta.txt",sep="_"),OUM_ouwie_8state_theta,row.names=F,sep="\t")
	write.table(file=paste(name,"t4_OUM_ouwie_3state_theta.txt",sep="_"),OUM_ouwie_3state_theta,row.names=F,sep="\t")
	write.table(file=paste(name,"t4_OUM_ouwie_2state_theta.txt",sep="_"),OUM_ouwie_2state_theta,row.names=F,sep="\t")

	# These commands summarize the OUwie results into minimum AICc vals over 100 trees
	t2_mins <- apply(t2_ouwie,1,function(x) {names(which.min(x))})
	t2_min_counts <- table(t2_mins)
	write.table(t2_min_counts,file=paste(name,"t2_min_counts.txt",sep="_"),row.names=F,sep="\t")
	
	t2_avgs <- apply(t2_ouwie,2,mean)
	write.table(t2_avgs,file=paste(name,"t2_avgs.txt",sep="_"),col.names=F,sep="\t")

	t4_OUM_ouwie_8state_avgs <- round(exp(apply(OUM_ouwie_8state_theta,2,mean)),digits=2)
	t4_OUM_ouwie_3state_avgs <- round(exp(apply(OUM_ouwie_3state_theta,2,mean)),digits=2)
	t4_OUM_ouwie_2state_avgs <- round(exp(apply(OUM_ouwie_2state_theta,2,mean)),digits=2)

	names(t4_OUM_ouwie_8state_avgs) <- nam
	names(t4_OUM_ouwie_3state_avgs) <- nam2
	names(t4_OUM_ouwie_2state_avgs) <- nam3

	write.table(t4_OUM_ouwie_8state_avgs,file=paste(name,"t4_OUM_ouwie_8state_avgs.txt",sep="_"),col.names=F,sep="\t")
	write.table(t4_OUM_ouwie_3state_avgs,file=paste(name,"t4_OUM_ouwie_3state_avgs.txt",sep="_"),col.names=F,sep="\t")
	write.table(t4_OUM_ouwie_2state_avgs,file=paste(name,"t4_OUM_ouwie_2state_avgs.txt",sep="_"),col.names=F,sep="\t")

	write.table(t4_OUM_ouwie_8state_avgs,file=paste(name,"t4_OUM_ouwie_8state_avgs.txt",sep="_"),col.names=F,sep="\t")
	write.table(t4_OUM_ouwie_3state_avgs,file=paste(name,"t4_OUM_ouwie_3state_avgs.txt",sep="_"),col.names=F,sep="\t")
	write.table(t4_OUM_ouwie_2state_avgs,file=paste(name,"t4_OUM_ouwie_2state_avgs.txt",sep="_"),col.names=F,sep="\t")

	write.table(t4_OUM_ouwie_8state_avgs,file=paste(name,"t4_OUM_ouwie_8state_avgs.txt",sep="_"),col.names=F,sep="\t")
	write.table(t4_OUM_ouwie_3state_avgs,file=paste(name,"t4_OUM_ouwie_3state_avgs.txt",sep="_"),col.names=F,sep="\t")
	write.table(t4_OUM_ouwie_2state_avgs,file=paste(name,"t4_OUM_ouwie_2state_avgs.txt",sep="_"),col.names=F,sep="\t")

}

run_adult_pgls_analyses <- function(trees,logs,name){

	# These commands generate data tables formatted for each specific program
	# These commands subset to include the maximum data for each analysis
	# "NA" and "Inf" data points are omitted, and ecological states are set to numerical
	
	# In all of the following, onum = ovariole number, thvl = thorax volume
	# prop = proportional egg volume, eggs = egg volume, tf = terminal filament
	# tfc = terminal filament cell, tot = total

	onum_thvl_pgls <- data.frame(onum=logs$onum,thor_vol=logs$thor_vol,row.names=logs$species) %>% na.omit()
	onum_eggs_pgls <- data.frame(onum=logs$onum,eggs=logs$egg_vol,row.names=logs$species) %>% na.omit()
	eggs_thvl_pgls <- data.frame(eggs=logs$egg_vol,thor_vol=logs$thor_vol,row.names=logs$species) %>% na.omit()
	onum_prop_pgls <- logs %>% select(onum,prop,species) %>% filter(is.finite(prop))
	onum_prop_pgls <- data.frame(onum=onum_prop_pgls$onum, prop=onum_prop_pgls$prop, row.names = onum_prop_pgls$species) %>% na.omit()
	onum_eggs_resid_pgls <- data.frame(onum_resid=logs$onum_resid,eggs_resid=logs$eggs_resid,row.names=logs$species) %>% na.omit()

	# These commands run PGLS for two traits at a time over 100 trees
	onum_thvl_pgls_out <- lapply(trees,pgls.trees,dat = onum_thvl_pgls,form = "onum~thor_vol")
	onum_eggs_pgls_out <- lapply(trees,pgls.trees,dat = onum_eggs_pgls,form = "onum~eggs")
	eggs_thvl_pgls_out <- lapply(trees,pgls.trees,dat = eggs_thvl_pgls,form = "eggs~thor_vol")
	onum_prop_pgls_out <- lapply(trees,pgls.trees,dat = onum_prop_pgls,form = "onum~prop")
	onum_eggs_resid_pgls_out <- lapply(trees,pgls.trees,dat = onum_eggs_resid_pgls,form = "onum_resid~eggs_resid")

	# These commands build dataframes from the results of the PGLS
	t1_adult_pgls <- matrix(ncol=20,nrow=length(trees))
	colnames(t1_adult_pgls) <- c("onum_thvl_slope","onum_thvl_pval","onum_thvl_alpha","onum_thvl_AIC_OU","onum_eggs_slope","onum_eggs_pval","onum_eggs_alpha","onum_eggs_AIC_OU","eggs_thvl_slope","eggs_thvl_pval","eggs_thvl_alpha","eggs_thvl_AIC_OU","onum_prop_slope","onum_prop_pval","onum_prop_alpha","onum_prop_AIC_OU","onum_eggs_resid_slope","onum_eggs_resid_pval","onum_eggs_resid_alpha","onum_eggs_resid_AIC_OU")
	
	for (i in 1:length(trees)){
		t1_adult_pgls[i,1] <- summary(onum_thvl_pgls_out[[i]])$tTable[[2]]
		t1_adult_pgls[i,2] <- summary(onum_thvl_pgls_out[[i]])$tTable[[8]]
		t1_adult_pgls[i,3] <- summary(onum_thvl_pgls_out[[i]])$modelStruct[[1]][[1]]
		t1_adult_pgls[i,4] <- summary(onum_thvl_pgls_out[[i]])$AIC
		t1_adult_pgls[i,5] <- summary(onum_eggs_pgls_out[[i]])$tTable[[2]]
		t1_adult_pgls[i,6] <- summary(onum_eggs_pgls_out[[i]])$tTable[[8]]
		t1_adult_pgls[i,7] <- summary(onum_eggs_pgls_out[[i]])$modelStruct[[1]][[1]]
		t1_adult_pgls[i,8] <- summary(onum_eggs_pgls_out[[i]])$AIC
		t1_adult_pgls[i,9] <- summary(eggs_thvl_pgls_out[[i]])$tTable[[2]]
		t1_adult_pgls[i,10] <- summary(eggs_thvl_pgls_out[[i]])$tTable[[8]]
		t1_adult_pgls[i,11] <- summary(eggs_thvl_pgls_out[[i]])$modelStruct[[1]][[1]]
		t1_adult_pgls[i,12] <- summary(eggs_thvl_pgls_out[[i]])$AIC
		t1_adult_pgls[i,13] <- summary(onum_prop_pgls_out[[i]])$tTable[[2]]
		t1_adult_pgls[i,14] <- summary(onum_prop_pgls_out[[i]])$tTable[[8]]
		t1_adult_pgls[i,15] <- summary(onum_prop_pgls_out[[i]])$modelStruct[[1]][[1]]
		t1_adult_pgls[i,16] <- summary(onum_prop_pgls_out[[i]])$AIC
		t1_adult_pgls[i,17] <- summary(onum_eggs_resid_pgls_out[[i]])$tTable[[2]]
		t1_adult_pgls[i,18] <- summary(onum_eggs_resid_pgls_out[[i]])$tTable[[8]]
		t1_adult_pgls[i,19] <- summary(onum_eggs_resid_pgls_out[[i]])$modelStruct[[1]][[1]]
		t1_adult_pgls[i,20] <- summary(onum_eggs_resid_pgls_out[[i]])$AIC
	}

	# This command writes PGLS results to a table
	write.table(file=paste(name,"t1.txt",sep="_"),t1_adult_pgls,row.names=F,sep="\t")

	# These commands summarize PGLS results into max, min, and avgs and write to files
	t1_avgs <- apply(t1_adult_pgls,2,mean)
	write.table(t1_avgs,file=paste(name,"t1_avgs.txt",sep="_"),col.names=F,sep="\t")
	t1_min <- apply(t1_adult_pgls,2,min)
	write.table(t1_min,file=paste(name,"t1_min.txt",sep="_"),col.names=F,sep="\t")
	t1_max <- apply(t1_adult_pgls,2,max)
	write.table(t1_max,file=paste(name,"t1_max.txt",sep="_"),col.names=F,sep="\t")
}

run_larval_pgls_analyses  <- function(trees,logs,name){
	
	# These commands generate data tables formatted for each specific program
	# These commands subset to include the maximum data for each analysis
	# "NA" and "Inf" data points are omitted, and ecological states are set to numerical
	
	# In all of the following, onum = ovariole number, thvl = thorax volume
	# prop = proportional egg volume, eggs = egg volume, tf = terminal filament
	# tfc = terminal filament cell, tot = total
	
	tfnum_tfcper <- data.frame(tf_num=logs$tf_num,tfc_tf=logs$tfc_tf,row.names=logs$species) %>% na.omit()
	tfnum_tottfc <- data.frame(tf_num=logs$tf_num,total_tfc=logs$total_tfc,row.names=logs$species) %>% na.omit()
	tfcper_tottfc <- data.frame(tfc_tf=logs$tfc_tf,total_tfc=logs$total_tfc,row.names=logs$species) %>% na.omit()

	# Thes commands run the PGSL analyses over 100 trees for the larval data

	tfnum_tfcper_pgls_out <- lapply(trees,pgls.trees,dat = tfnum_tfcper,form = "tf_num~tfc_tf")
	tfnum_tottfc_pgls_out <- lapply(trees,pgls.trees,dat = tfnum_tottfc,form = "tf_num~total_tfc")
	tfcper_tottfc_pgls_out <- lapply(trees,pgls.trees,dat = tfcper_tottfc,form = "tfc_tf~total_tfc")

	# These commands build dataframes from the results of the PGLS

	t3_larval_pgls <- matrix(ncol=12,nrow=length(trees))
	colnames(t3_larval_pgls) <- c("tfnum_tfcper_slope","tfnum_tfcper_pval","tfnum_tfcper_alpha","tfnum_tfcper_AIC_OU","tfnum_tottfc_slope","tfnum_tottfc_pval","tfnum_tottfc_alpha","tfnum_tottfc_AIC_OU","tfcper_tottfc_slope","tfcper_tottfc_pval","tfcper_tottfc_alpha","tfcper_tottfc_AIC_OU")
	
	for (i in 1:length(trees)){
		t3_larval_pgls[i,1] <- summary(tfnum_tfcper_pgls_out[[i]])$tTable[[2]]
		t3_larval_pgls[i,2] <- summary(tfnum_tfcper_pgls_out[[i]])$tTable[[8]]
		t3_larval_pgls[i,3] <- summary(tfnum_tfcper_pgls_out[[i]])$modelStruct[[1]][[1]]
		t3_larval_pgls[i,4] <- summary(tfnum_tfcper_pgls_out[[i]])$AIC
		t3_larval_pgls[i,5] <- summary(tfnum_tottfc_pgls_out[[i]])$tTable[[2]]
		t3_larval_pgls[i,6] <- summary(tfnum_tottfc_pgls_out[[i]])$tTable[[8]]
		t3_larval_pgls[i,7] <- summary(tfnum_tottfc_pgls_out[[i]])$modelStruct[[1]][[1]]
		t3_larval_pgls[i,8] <- summary(tfnum_tottfc_pgls_out[[i]])$AIC
		t3_larval_pgls[i,9] <- summary(tfcper_tottfc_pgls_out[[i]])$tTable[[2]]
		t3_larval_pgls[i,10] <- summary(tfcper_tottfc_pgls_out[[i]])$tTable[[8]]
		t3_larval_pgls[i,11] <- summary(tfcper_tottfc_pgls_out[[i]])$modelStruct[[1]][[1]]
		t3_larval_pgls[i,12] <- summary(tfcper_tottfc_pgls_out[[i]])$AIC
	}

	# This command writes PGLS results to a table
	write.table(file=paste(name,"t3.txt",sep="_"),t3_larval_pgls,row.names=F,sep="\t")

	# These commands summarize PGLS results into max, min, and avgs and write to files
	t3_avgs <- apply(t3_larval_pgls,2,mean)
	write.table(t3_avgs,file=paste(name,"t3_avgs.txt",sep="_"),col.names=F,sep="\t")
	t3_min <- apply(t3_larval_pgls,2,min)
	write.table(t3_min,file=paste(name,"t3_min.txt",sep="_"),col.names=F,sep="\t")
	t3_max <- apply(t3_larval_pgls,2,max)
	write.table(t3_max,file=paste(name,"t3_max.txt",sep="_"),col.names=F,sep="\t")
}

### 7 main blocks of analyses in this study ###

# (1/7) Phylogenetic methods using all available genetic and phenotypic data
# Using all the data, on the BEAST trees with all available sequence data
run_ouwie_analyses(all_trees,onum_logs,"all_all_onum")
run_ouwie_analyses(all_trees,prop_logs,"all_all_prop")
run_ouwie_analyses(all_trees,thvl_logs,"all_all_thvl")
run_ouwie_analyses(all_trees,eggs_logs,"all_all_eggs")
run_ouwie_analyses(all_trees,eggs_resid_logs,"all_all_eggs_resid")
run_adult_pgls_analyses(all_trees,logs,"all_all")
run_larval_pgls_analyses(all_trees,logs,"all_all")

# Phylogenetic methods using all the phenotypic data data, on the BEAST trees with only mitochondrial sequence data
run_ouwie_analyses(mito_trees,onum_logs,"mito_trees_onum")
run_ouwie_analyses(mito_trees,prop_logs,"mito_trees_prop")
run_ouwie_analyses(mito_trees,thvl_logs,"mito_trees_thvl")
run_ouwie_analyses(mito_trees,eggs_logs,"mito_trees_eggs")
run_ouwie_analyses(mito_trees,eggs_resid_logs,"mito_trees_eggs_resid")
run_adult_pgls_analyses(mito_trees,logs,"new_mito")
run_larval_pgls_analyses(mito_trees,logs,"new_mito")

# (2/7) Using only modified mouthparts, analyze over each set of 100 trees
group_name = "mouth"
new_logs <- logs %>% filter(group == group_name)
run_adult_pgls_analyses(all_trees,new_logs,paste(group_name,"all",sep="_"))
run_adult_pgls_analyses(mito_trees,new_logs,paste(group_name,"mito",sep="_"))

# (3/7) Using only Scaptomyza, analyze over each set of 100 trees
group_name = "scapto"
new_logs <- logs %>% filter(group == group_name)
run_adult_pgls_analyses(all_trees,new_logs,paste(group_name,"all",sep="_"))
run_adult_pgls_analyses(mito_trees,new_logs,paste(group_name,"mito",sep="_"))

# (4/7) Using only PNA, analyze over each set of 100 trees
group_name = "pna"
new_logs <- logs %>% filter(group == group_name)
run_adult_pgls_analyses(all_trees,new_logs,paste(group_name,"all",sep="_"))
run_adult_pgls_analyses(mito_trees,new_logs,paste(group_name,"mito",sep="_"))

# (5/7) Using only AMC, analyze over each set of 100 trees
group_name = "amc"
new_logs <- logs %>% filter(group == group_name)
run_adult_pgls_analyses(all_trees,new_logs,paste(group_name,"all",sep="_"))
### mito trees fail for AMC due to limited data with almost no signal at all, singular convergence problems
###run_adult_pgls_analyses(mito_trees,new_logs,paste(group_name,"mito",sep="_"))

# (6/7) Using only Sarikaya collected data, analyze over each set of 100 trees
author_name = "Sari"

# These commands rebuild the datasets using only Sarikaya collected data
dat <- read.table("data.txt",header=T) %>% 
		filter(author == author_name) %>% 
		group_by(species) %>% 
		summarize_if(is.numeric,funs(mean),na.rm=T) 

mg <- merge(dat,eco,by="species")
write.table(mg,file="Sari_avgs.txt",row.names=FALSE,sep="\t")
avgs <- read.delim("Sari_avgs.txt")
logs <- avgs %>% mutate(
	thor = log(thorax),
	thor_vol = log(thor_vol),
	onum = log(onum),
	dors = log(dors),
	egg_vol = log(egg_vol),
	major = log(major),
	minor = log(minor),
	prop = log(prop),
	tf_num = log(tf_num),
	tfc_tf = log(tfc_tf),
	total_tfc = log(total_tfc))

write.table(logs,file="Sari_logs.txt",row.names=FALSE,sep="\t")

reduced_logs <- logs %>% 
			filter(species %in% all_trees[[1]]$tip.label) %>%
			mutate(trait1 = egg_vol, trait2 = onum, indep = thor_vol) %>% 
			select(species,trait1,trait2,indep) %>% 
			na.omit()
Y <- data.frame(trait1 = reduced_logs$trait1, trait2 = reduced_logs$trait2 ,row.names=reduced_logs$species)
X <- reduced_logs$indep
names(X) <- reduced_logs$species
pruned <- drop.tip(all_trees[[1]],tip=setdiff(all_trees[[1]]$tip.label,reduced_logs$species))
resid <- data.frame((phyl.resid(pruned,X,Y,method="BM")$resid))
logs <- left_join(logs,tibble::rownames_to_column(resid,var = "species"),by = "species") %>% rename(eggs_resid = trait1, onum_resid = trait2)

new_logs <- logs
new_onum_logs <- logs %>% mutate(trait = onum)

run_ouwie_analyses(all_trees,new_onum_logs,paste(author_name,"all_trees_onum",sep="_"))
run_ouwie_analyses(mito_trees,new_onum_logs,paste(author_name,"mito_trees_onum",sep="_"))
run_adult_pgls_analyses(all_trees,new_logs,paste(author_name,"all",sep="_"))
run_adult_pgls_analyses(mito_trees,new_logs,paste(author_name,"mito",sep="_"))
run_larval_pgls_analyses(all_trees,new_logs,paste(author_name,"all",sep="_"))
run_larval_pgls_analyses(mito_trees,new_logs,paste(author_name,"mito",sep="_"))

# (7/7) With alternative proxy IDS, analyze over each set of 100 trees
# These commands rebuild the datasets using alternative proxy IDs
dat <- read.table("data.txt",header=T)
dat$species <- dat$species2	
dat <- dat %>% 
		group_by(species) %>% 
		summarize_if(is.numeric,funs(mean),na.rm=T) 

mg <- merge(dat,eco,by="species")
write.table(mg,file="sp2_avgs.txt",row.names=FALSE,sep="\t")
avgs <- read.delim("sp2_avgs.txt")
logs <- avgs %>% mutate(
	thor = log(thorax),
	thor_vol = log(thor_vol),
	onum = log(onum),
	dors = log(dors),
	egg_vol = log(egg_vol),
	major = log(major),
	minor = log(minor),
	prop = log(prop),
	tf_num = log(tf_num),
	tfc_tf = log(tfc_tf),
	total_tfc = log(total_tfc))

write.table(logs,file="sp2_logs.txt",row.names=FALSE,sep="\t")

reduced_logs <- logs %>% 
			filter(species %in% all_trees[[1]]$tip.label) %>%
			mutate(trait1 = egg_vol, trait2 = onum, indep = thor_vol) %>% 
			select(species,trait1,trait2,indep) %>% 
			na.omit()
Y <- data.frame(trait1 = reduced_logs$trait1, trait2 = reduced_logs$trait2 ,row.names=reduced_logs$species)
X <- reduced_logs$indep
names(X) <- reduced_logs$species
pruned <- drop.tip(all_trees[[1]],tip=setdiff(all_trees[[1]]$tip.label,reduced_logs$species))
resid <- data.frame((phyl.resid(pruned,X,Y,method="BM")$resid))
logs <- left_join(logs,tibble::rownames_to_column(resid,var = "species"),by = "species") %>% rename(eggs_resid = trait1, onum_resid = trait2)

new_logs <- logs
new_onum_logs <- logs %>% mutate(trait = onum)

run_ouwie_analyses(all_trees,new_onum_logs,"sp2_all_trees_onum")
run_ouwie_analyses(mito_trees,new_onum_logs,"sp2_mito_trees_onum")
run_adult_pgls_analyses(all_trees,new_logs,"sp2_all_all")
run_adult_pgls_analyses(mito_trees,new_logs,"sp2_new_mito")
run_larval_pgls_analyses(all_trees,new_logs,"sp2_all_all")
run_larval_pgls_analyses(mito_trees,new_logs,"sp2_new_mito")


